### ISSUE TITLE
Makeing mainmatter one column

### ISSUE THREAD

**Issue by anthillsocial** [qualiacode/arabica#1]
Hi,

Any advice for making the layout one column rather than two?
SImply removing '- 'twocolumn'  from the class option in settings/00_00_settings.yaml 
 doesn't seem to make a difference...

Tom

**Comment by periodicpoint** [comment]
Hi Tom,

telling your LaTeX compiler (e.g. XeLaTeX see PS) explicitly that you want to have a one-column layout by substituting `-'twocolumn'` with `-'onecolumn'` in `/00_00_settings.yaml` should do the trick.

For a two-side, one-column layout your settings should look something like:
```
classoption:
  - 'twoside'
  - 'onecolumn'
```

For one-side, one-column layout:
```
classoption:
  - 'oneside'
  - 'onecolumn'
```

Let me know if it works.

Cheers,
Martin

PS: With the arabica boilerplate your LaTeX compiler gets invoked by pandoc via the command line argument  `--pdf-engine=xelatex`. [See also the pandoc manual for more information](https://pandoc.org/MANUAL.html)

**Comment by anthillsocial** [comment]
Thanks for that Martin,
So I did some tests and your suggestion does work... However, I have discovered that adding a table in the following MD format causes the onecolumn layout to revert to twocolumn for any subsequent pages: 

    ---------------    ------------------------------------------------------- 
    DC                 Department for Communities
    FOIA               Freedom of Information Act
    ---------------    -------------------------------------------------------`

So it was the introduction of my markdown that revealed the bug. Any suggestions for fixing this?
Tom

**Comment by periodicpoint** [comment]
Thanks for pointing this out, @anthillsocial. This was indeed a bug.

This bug was introduced because I adopted a hack form [nrnrnr@github](https://GitHub.com/jgm/pandoc/issues/1023) and [Marco Torchian@tex.stackexchange](https://tex.stackexchange.com/questions/161431/how-to-solve-longtable-is-not-in-1-column-mode-error?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).  I incorporated this hack into the template file `arabica.latex` because by default pandoc uses the LaTeX package [longtable](https://ctan.org/pkg/longtable?lang=en) to

> allow tables to flow over page boundaries.

The `longtable.sty` package works fine for documents in one-column mode. As far as I know it does **not** work with documents in two-column mode. To make the two-column mode and the longtable package work together we have to redefine `\longtable ` (see [Marco Torchian@tex.stackexchange](https://tex.stackexchange.com/questions/161431/how-to-solve-longtable-is-not-in-1-column-mode-error?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)).

I changed the redefinition of `\longtable`. The redefinition now entails a snipped to switch back to the one-column/two-column mode conditionally depending on the given class option for the `scrbook` class. You should now be able to switch back and forth between one-column/two-column mode for your document by setting the according values in the `00_00_settings.yaml` file i.g. `- 'onecolumn'` or  `- 'twocolumn'` respectively.

I hope this solves the issue.

Cheers

**Comment by anthillsocial** [comment]
Thank's Martin - all working as expected now. Literally, as I received your message I worked what the problem was - i'm relatively new to Latex so it been a bit of a learning curve!
Tom
