### ISSUE TITLE
error producing pdf

### ISSUE THREAD

**Issue by VP59m** [qualiacode/arabica#3]
Hi all! I followed step by step the amazing wiki but shell returns this error
`Error producing PDF.
! Missing \endcsname inserted.
<to be read again> 
                   \TU\textasciitilde 
l.86       \usetikzlibrary{\textasciitilde{}}
`
Any ideas?
cheers Igor

**Comment by periodicpoint** [comment]
Hi @VP59m,

thank you for reporting this bug.

# BLUF
1. I fixed the bug you can update now and try again.
2. Your error is most likely caused by the tilde symbol “~” in file 00_00_settings.yaml at line 269 at “usetusetikzlibrary:”. Removing the tilde should fix your error.

# TL;DR
## Cause
The error is caused by the ASCII tilde symbol “~” in the settings or metadata files. Here most likely at line 269 at “usetikzlibrary:“.

## Explanation
In the general YAML treats tildes as NULL.
The error message: „Error producing PDF. ! Missing \endcsname inserted. \TU\textasciitilde l.86 \usetikzlibrary{\textasciitilde{}}“ is caused by the existence of the tilde symbol in the metadata or settings (YAML) file, because pandoc translates occurrences tildes of into “\textasciitilde{}”. The LaTeX compiler (XeTeX) do not like “\textasciitilde{}” inside of “\usepackage{}” or “\usetikzlibrary{}”.

## Fix
Remove every occurrence of “~” in the settings and metadata files.

I hope it helps.

Cheers,
Martin

PS: Please note that I regard arabica not stable at the moment. I'll probably completely redesign arabica in the near future. I plan to simplify the entire thing, but this may be breaking changes. …

**Comment by VP59m** [comment]
thank you so much :)
